export const GAME_SAVE_DATA_USER = "GAME_SAVE_DATA_USER";
export const GAME_SHOW_DATA_USER = "GAME_SHOW_DATA_USER";
export const GAME_SAVE_DATA_BOARD_TRAINING_WITH_YOURSELF = "GAME_SAVE_DATA_BOARD_TRAINING_WITH_YOURSELF";
export const GAME_SAVE_DATA_BOARD_TRAINING_WITH_AI = "GAME_SAVE_DATA_BOARD_TRAINING_WITH_AI";
// export const GAME_SHOW_DATA_ALL_USERS = "GAME_SHOW_DATA_ALL_USERS";